name: Project8
run-name: ${{ github.actor }} is generating the Verilog files. 🚀
on: [push]
jobs:
    
  Project8-Build-And-Generate:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OCAML
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true
      - name: Install Hardcaml and dependencies
        run: |
          # Change to your project subdirectory
          cd project8/spi_hardcaml
          # Install dependencies required by the .opam file
          opam install . --deps-only --with-test
          # Manually install Hardcaml and ppx_hardcaml
          # (This step is often not needed if included in your .opam file)
          opam install hardcaml ppx_hardcaml
        
